// ─── Task ────────────────────────────────────────────────────────────────────

export type TaskType = "microtask" | "macrotask";

export type TaskStatus =
  | "queued"
  | "moving-to-event-loop"
  | "event-loop"
  | "moving-to-stack"
  | "executing"
  | "completed";

export interface Task {
  id: string;
  label: string;
  type: TaskType;
  status: TaskStatus;
  createdAt: number;
  schedules?: { type: TaskType } | null;
  parentId?: string;
  scheduledTasks?: Task[];  // Nested child tasks enqueued when this task runs
  consoleLogs?: string[];   // Console output logs generated by this task
  executionTicks?: Array<{ event: string; type: string }>;
}

// ─── Log Entry ────────────────────────────────────────────────────────────────

export type LogType = "info" | "micro" | "macro" | "system";

export interface LogEntry {
  id: string;
  timestamp: number;
  message: string;
  type: LogType;
}

// ─── Timeline Tick ────────────────────────────────────────────────────────────

export interface TimelineTick {
  id: string;
  tick: number;
  taskId: string;
  taskLabel: string;
  taskType: TaskType;
  event: string;
  timestamp: number;
}

// ─── Phase Entry (for visual phase timeline) ──────────────────────────────────

export interface PhaseEntry {
  id: string;
  phaseNumber: number;
  /** "global-script", "microtask-drain" or "macrotask" */
  kind: "global-script" | "microtask-drain" | "macrotask";
  label: string;
  taskCount: number; // how many tasks in this phase
  status: "pending" | "active" | "completed";
  startedAt: number;
}


// ─── Runtime Phase ────────────────────────────────────────────────────────────

export type RuntimePhase =
  | "idle"
  | "draining-microtasks"
  | "executing-macrotask"
  | "executing-task";

// ─── Scenarios & Presets ──────────────────────────────────────────────────────

export type CallStackScenario = "empty" | "busy-sync";

export type ScenarioPreset =
  | "basic"
  | "call-stack-busy"
  | "macro-schedules-micro"
  | "nested-microtasks";

// ─── Runtime State ────────────────────────────────────────────────────────────

export interface RuntimeState {
  callStack: Task[];
  microtaskQueue: Task[];
  macrotaskQueue: Task[];
  completedTasks: Task[];
  currentTask: Task | null;
  /**
   * Number of completed Event Loop phases.
   * One microtask-drain batch = 1 phase.
   * One macrotask = 1 phase.
   * 10 micros + 20 macros → 21 phases total.
   */
  currentPhaseNumber: number;
  tasksExecuted: number;
  currentPhase: RuntimePhase;
  isRunning: boolean;
  isPaused: boolean;
  speed: number;
  executionLogs: LogEntry[];
  timelineTicks: TimelineTick[];
  tickCounter: number;
  callStackScenario: CallStackScenario;
  educationalText: string;
  consoleOutput: string[];     // Console output strings printed so far
  expectedOutput: string[];    // Expected console outputs (predicted statically)
  analyzerCode: string;        // Active analyzer code
}

// ─── Speed Config ─────────────────────────────────────────────────────────────

export const SPEED_MULTIPLIERS = [0.1, 0.25, 0.5, 1, 2, 5, 10] as const;
export type SpeedMultiplier = (typeof SPEED_MULTIPLIERS)[number];


// ─── Timing (at 1x speed, ms) ─────────────────────────────────────────────────

export const BASE_TIMING = {
  queueToEventLoop: 300,
  eventLoopToStack: 200,
  executing: 600,
  completing: 400,
} as const;

// ─── Microtask label variants ─────────────────────────────────────────────────

export const MICROTASK_LABELS = [
  "Promise.then()",
  "queueMicrotask()",
  "Promise.resolve()",
  ".catch()",
  ".finally()",
] as const;

export const MACROTASK_LABELS = [
  "setTimeout()",
  "setInterval()",
  "MessageChannel",
  "requestAnimationFrame()",
  "I/O callback",
] as const;
